# Generated by Django 3.0.3 on 2022-06-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='updation',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('uploading', models.FileField(upload_to='upload/')),
            ],
        ),
    ]
